Repository PerformanC/ReZygisk, pull requests merged in 2024-11, with the labels that each got.

#79 New Lines for Chinese Simplified
  webroot/lang/zh_CN.json
Labels: enhancement

#80 Update README_CN.md
  README_CN.md
Labels: confirmed, enhancement

#84 Add: Traditional Chinese README.md.
  README.md
  READMEs/README_zh-CN.md
  READMEs/README_zh-TW.md
Labels: confirmed, enhancement

#91 Trigger Zygisk modules service.sh in parallel
  .github/workflows/ci.yml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  module/src/service.sh
Labels: bug, confirmed
