Repository PerformanC/ReZygisk, pull requests merged in 2025-04, with the labels that each got.

#100 Add Ukrainian translations to WebUI
  TRANSLATOR.md
  webroot/lang/uk_UA.json
Labels: confirmed, enhancement

#130 Update sepolicy.rule
  module/src/sepolicy.rule
Labels: bug, confirmed

#99 fix zygisk failing on grapheneos
  loader/src/injector/gen_jni_hooks.py
  loader/src/injector/jni_hooks.hpp
Labels: bug, confirmed

#122 Port more of the codebase to C; Fix general bugs
  loader/build.gradle.kts
  loader/src/CMakeLists.txt
  loader/src/common/daemon.c
  loader/src/common/daemon.cpp
  loader/src/common/elf_util.c
  loader/src/common/elf_util.cpp
  loader/src/common/files.cpp
  loader/src/common/misc.c
  loader/src/common/misc.cpp
  loader/src/common/socket_utils.c
  loader/src/common/socket_utils.cpp
  loader/src/include/daemon.h
  loader/src/include/elf_util.h
  loader/src/include/files.hpp
  loader/src/include/misc.h
  loader/src/include/misc.hpp
  loader/src/include/native_bridge_callbacks.h
  loader/src/include/socket_utils.h
  loader/src/include/solist.hpp
  loader/src/injector/art_method.hpp
  loader/src/injector/entry.cpp
  loader/src/injector/hook.cpp
  loader/src/injector/solist.c
  loader/src/injector/solist.h
  loader/src/ptracer/main.c
  loader/src/ptracer/monitor.c
  loader/src/ptracer/monitor.cpp
  loader/src/ptracer/monitor.h
  loader/src/ptracer/ptracer.c
  loader/src/ptracer/utils.c
  loader/src/ptracer/utils.cpp
  loader/src/ptracer/utils.h
  loader/src/ptracer/utils.hpp
  zygiskd/src/constants.h
  zygiskd/src/utils.h
  zygiskd/src/zygiskd.c
Labels: bug, confirmed, enhancement

#152 Update README_fr-FR.md
  READMEs/README_fr-FR.md
Labels: bug, confirmed
